version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./:/server/
      - /server/node_modules
    env_file:
      - .env
    ports:
      - 3006:3006
    depends_on:
      - db
  
  db:
    image: postgres:12.6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
